#!/opt/pwn.college/python

from subprocess import Popen, PIPE
import os.path
import sys

if len(sys.argv) <= 1:
    print("Welcome to snakelet01! Please write a Python3 file with a print statement that says \"Hello World\" in it!")
    exit()

fileName = sys.argv[1]

if not os.path.isfile(fileName):
    print("ERROR: File Does Not Exist")
else:
    output = Popen(['python3', fileName], stdout=PIPE)
    txtOut = output.communicate[0]
    print("Code output: " + txtOut)

    if txtOut.lower() == "hello world":
        print("They are equal")
        with open("/flag") as f:
            print(f.read())
