#!/opt/pwn.college/python

import subprocess
import os.path
import sys

if len(sys.argv) <= 1:
    print("Welcome to snakelet01! Please write a Python3 file with a print statement that says \"Hello World\" in it!")
    exit()

fileName = sys.argv[1]

if not os.path.isfile(fileName):
    print("ERROR: File does not exist")
else:
    process = subprocess.run(['python3', fileName], stdout=subprocess.PIPE)
    txtOut = process.stdout.decode()
    print("Code output: " + txtOut)

    if txtOut.strip().lower() == "hello world":
        print("They are equal! Here is your flag!")
        with open("/flag") as f:
            print(f.read())
    else:
        print("Sorry, they did not match! Try again!")
