#!/opt/pwn.college/python

import subprocess
import os.path
import sys
import random 
import base64
import string


    

if len(sys.argv) <= 1:
    print("We are going to reverse the roles this challenge.")
    print("For this challenge, you will need to use these lines of code:")
    print("\timport sys")
    print("\targ1 = sys.argv[1]")
    print("arg1 is going to be the filename that your program will READ.")
    print("To get the flag, read the file and print its contents!")
    
    exit()

fileName = sys.argv[1]

async def CreateFile(fileN):
    process = await subprocess.run(['python3', fileName, fileN], stdout=subprocess.PIPE)
    return await process.stdout.decode()

if not os.path.isfile(fileName):
    print("ERROR: File does not exist")
else:
    with open("/flag") as f:
        fileWrite = ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k=8))
        fileP = open(fileWrite + ".txt", "w")
        fileP.write(f.read())
        txtOut = CreateFile(fileWrite + ".txt")
        print("Code output: " + txtOut.strip())
        os.remove(fileWrite + ".txt")
