#!/opt/pwn.college/python

import subprocess
import os.path
import sys
import random 
import base64
import string
import time

if len(sys.argv) <= 1:
    print("We are going to reverse the roles this challenge.")
    print("For this challenge, you will need to use these lines of code:")
    print("\timport sys")
    print("\targ1 = sys.argv[1]")
    print("arg1 is going to be the filename that your program will READ.")
    print("To get the flag, read the file and print its contents!")
    
    exit()

fileName = sys.argv[1]

if not os.path.isfile(fileName):
    print("ERROR: File does not exist")
else:
    with open("/flag") as f:
        secretMessage = ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k=8))

        fileP = open("secretmessage.txt", "w")
        fileP.write(secretMessage)
        fileP.close()

        process = subprocess.run(['python3', fileName, "secretmessage.txt"], stdout=subprocess.PIPE)
        txtOut = process.stdout.decode()
        print("Code output: " + txtOut.strip())

        if txtOut.strip() == secretMessage:
            print(f.read())
            os.remove("secretmessage.txt")
        else:
            print("Looks like it read the wrong file!")
